// The Sweeter app icon: design/sweeter-icon-art.png (the painting, a full
// square) inside the macOS squircle (a superellipse, n = 5, 824 px across
// on a 1024 canvas) with a faint edge light, then every size the app, the
// Safari extension, and the page use. Run by scripts/icons.sh.
import CoreGraphics
import Foundation
import ImageIO
import UniformTypeIdentifiers

let root = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : FileManager.default.currentDirectoryPath
let sRGB = CGColorSpace(name: CGColorSpace.sRGB)!

func load(_ path: String) -> CGImage {
    guard let src = CGImageSourceCreateWithURL(URL(fileURLWithPath: path) as CFURL, nil), let img = CGImageSourceCreateImageAtIndex(src, 0, nil) else { fatalError("can't read " + path) }
    return img
}

func canvas(_ size: Int) -> CGContext {
    let ctx = CGContext(data: nil, width: size, height: size, bitsPerComponent: 8, bytesPerRow: 0, space: sRGB, bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    ctx.interpolationQuality = .high
    return ctx
}

func png(_ img: CGImage) -> Data {
    let data = NSMutableData()
    let dest = CGImageDestinationCreateWithData(data, UTType.png.identifier as CFString, 1, nil)!
    CGImageDestinationAddImage(dest, img, nil)
    CGImageDestinationFinalize(dest)
    return data as Data
}

func write(_ img: CGImage, _ path: String) {
    try! png(img).write(to: URL(fileURLWithPath: root + "/" + path))
}

func squircle(cx: CGFloat = 512, cy: CGFloat = 512, r: CGFloat = 412, n: CGFloat = 5, steps: Int = 720) -> CGPath {
    let p = CGMutablePath()
    for i in 0..<steps {
        let a = 2 * CGFloat.pi * CGFloat(i) / CGFloat(steps)
        let c = cos(a), s = sin(a)
        let pt = CGPoint(x: cx + r * copysign(pow(abs(c), 2 / n), c), y: cy + r * copysign(pow(abs(s), 2 / n), s))
        if i == 0 { p.move(to: pt) } else { p.addLine(to: pt) }
    }
    p.closeSubpath()
    return p
}

// The master, 1024 px. The painting is zoomed a little past the squircle
// (only sky is lost) so the bird fills it as the old drawn icon's did.
let zoom: CGFloat = 1.12
let art = load(root + "/design/sweeter-icon-art.png")
let ctx = canvas(1024)
let shape = squircle()
ctx.addPath(shape)
ctx.clip()
ctx.draw(art, in: CGRect(x: 0, y: 0, width: 824, height: 824).insetBy(dx: -824 * (zoom - 1) / 2, dy: -824 * (zoom - 1) / 2).offsetBy(dx: 100, dy: 100))
// The squircle's own edge light (half of a 4 px line, inside the clip).
ctx.addPath(shape)
ctx.setStrokeColor(CGColor(colorSpace: sRGB, components: [1, 1, 1, 0.35])!)
ctx.setLineWidth(4)
ctx.strokePath()
let master = ctx.makeImage()!
write(master, "design/icon-1024.png")

func scaled(_ size: Int) -> CGImage {
    let c = canvas(size)
    c.draw(master, in: CGRect(x: 0, y: 0, width: size, height: size))
    return c.makeImage()!
}

let set = "safari/Sweeter/Sweeter/Assets.xcassets/AppIcon.appiconset/"
for s in [16, 32, 128, 256, 512] {
    write(scaled(s), set + "mac-icon-\(s)@1x.png")
    write(scaled(s * 2), set + "mac-icon-\(s)@2x.png")
}
for s in [16, 32, 48, 96, 128, 256, 512] { write(scaled(s), "extension/icons/icon-\(s).png") }
write(scaled(512), "safari/Sweeter/Sweeter/Resources/Icon.png")
// The page shows it on the loading screen and the welcome (at most 104 pt).
let mark = png(scaled(256)).base64EncodedString()
let js = "// Generated by scripts/icons.sh from design/sweeter-icon-art.png. Do not edit.\n(function (root) {\n  (root.Sweeter || (root.Sweeter = {})).MARK = 'data:image/png;base64,\(mark)';\n})(typeof globalThis !== 'undefined' ? globalThis : this);\n"
try! js.write(toFile: root + "/extension/src/ui/mark.js", atomically: true, encoding: .utf8)
print("Icons exported from design/sweeter-icon-art.png")
