// Writes extension/src/ui/emoji.js, the emoji picker's data: every emoji in
// Unicode's emoji-test.txt (fully qualified, in Unicode's own order and
// groups), with its CLDR name and English search keywords, its Emoji
// version, and its five skin tones where it has them.
//
//   node scripts/emoji.mjs
//
// The sources are pinned below; change EMOJI and CLDR together when a new
// Emoji version ships. The picker hides emoji newer than the Mac can draw.
import fs from 'node:fs';
import path from 'node:path';

const EMOJI = '18.0.0';
const CLDR = '48.2.3';
const SRC = {
  test: `https://www.unicode.org/Public/${EMOJI}/emoji/emoji-test.txt`,
  ann: `https://raw.githubusercontent.com/unicode-org/cldr-json/${CLDR}/cldr-json/cldr-annotations-full/annotations/en/annotations.json`,
  derived: `https://raw.githubusercontent.com/unicode-org/cldr-json/${CLDR}/cldr-json/cldr-annotations-derived-full/annotationsDerived/en/annotations.json`,
};
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const OUT = path.join(root, 'extension/src/ui/emoji.js');

const get = async (u) => {
  const r = await fetch(u);
  if (!r.ok) throw new Error(u + ': HTTP ' + r.status);
  return r.text();
};
const [test, ann, derived] = await Promise.all([get(SRC.test), get(SRC.ann).then(JSON.parse), get(SRC.derived).then(JSON.parse)]);
const notes = Object.assign({}, derived.annotationsDerived.annotations, ann.annotations.annotations);

const TONES = [0x1f3fb, 0x1f3fc, 0x1f3fd, 0x1f3fe, 0x1f3ff];
// Sweeter's UI is in American English: CLDR's British names change, and keep
// the British word as a keyword; British keywords gain the American word.
const NAMES = { 'chequered flag': 'checkered flag', 'grey heart': 'gray heart', 'articulated lorry': 'semi truck' };
const WORDS = { aeroplane: 'airplane', axe: 'ax', chequered: 'checkered', colour: 'color', doughnut: 'donut', grey: 'gray', lorry: 'truck', moustache: 'mustache', postbox: 'mailbox', theatre: 'theater', torch: 'flashlight', whisky: 'whiskey' };
const noVS = (s) => s.replace(/️/g, '');
const groups = [];
const byBase = new Map(); // the emoji without FE0F -> its entry
let group = null;
for (const line of test.split('\n')) {
  const g = /^# group: (.+)$/.exec(line);
  if (g) {
    group = g[1] === 'Component' ? null : { name: g[1], list: [] };
    if (group) groups.push(group);
    continue;
  }
  const m = /^([0-9A-F ]+?)\s*; fully-qualified\s*# (\S+) E(\d+\.\d+) (.+)$/.exec(line);
  if (!m || !group) continue;
  const cps = m[1].split(' ').map((h) => parseInt(h, 16));
  const ch = String.fromCodePoint(...cps);
  const tones = cps.filter((c) => TONES.includes(c));
  if (tones.length) {
    // A skin-tone form: kept on its base, and only when every person in it
    // has the same tone (the mixed ones are left to the system picker).
    if (tones.some((t) => t !== tones[0])) continue;
    const base = byBase.get(noVS(String.fromCodePoint(...cps.filter((c) => !TONES.includes(c)))));
    if (!base) throw new Error('no base for ' + m[4]);
    base.tones[TONES.indexOf(tones[0])] = ch;
    continue;
  }
  const note = notes[ch] || notes[noVS(ch)] || {};
  const name = NAMES[m[4]] || m[4];
  const words = new Set(name.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean));
  const raw = (note.default || []).map((k) => k.toLowerCase()).concat(NAMES[m[4]] ? [m[4]] : []);
  for (const k of raw.slice()) for (const w of k.split(/\s+/)) if (WORDS[w]) raw.push(WORDS[w]);
  const keys = raw.filter((k) => k !== name.toLowerCase() && !k.split(/\s+/).every((w) => words.has(w)));
  const e = { ch, name, keys: Array.from(new Set(keys)), ver: Number(m[3]), tones: [] };
  group.list.push(e);
  byBase.set(noVS(ch), e);
}

// Tones the picker can make itself (the modifier right after the first
// character, which then drops its FE0F) are stored as 1; others in full.
const simple = (e, i) => {
  const cps = Array.from(e.ch);
  const rest = cps.slice(1);
  if (rest[0] === '️') rest.shift();
  return cps[0] + String.fromCodePoint(TONES[i]) + rest.join('');
};
let total = 0;
let toned = 0;
const data = groups.map((g) => [
  g.name,
  g.list.map((e) => {
    total++;
    const row = [e.ch, e.name, e.keys.join('|'), e.ver];
    if (e.tones.length) {
      if (e.tones.filter(Boolean).length !== 5) throw new Error('missing tones for ' + e.name);
      toned++;
      row.push(e.tones.every((t, i) => t === simple(e, i)) ? 1 : e.tones);
    }
    return row;
  }),
]);

const json = JSON.stringify({ v: EMOJI, g: data });
const out =
  '// Generated by scripts/emoji.mjs: do not edit by hand.\n' +
  `// Emoji, order, groups and versions: Unicode emoji-test.txt ${EMOJI}.\n` +
  `// Names and English keywords: Unicode CLDR ${CLDR} annotations.\n` +
  '// Copyright © 1991-2026 Unicode, Inc. Unicode License v3:\n' +
  '// https://www.unicode.org/license.txt\n' +
  '// Each emoji: [emoji, name, keywords joined by |, Emoji version, tones?],\n' +
  '// tones being 1 (the modifier after the first character) or the five forms.\n' +
  '// Kept as JSON text, parsed when the picker first opens.\n' +
  '(function (root) {\n' +
  "  'use strict';\n" +
  '  const Sweeter = root.Sweeter || (root.Sweeter = {});\n' +
  '  Sweeter.EMOJI_JSON = ' + JSON.stringify(json) + ';\n' +
  "})(typeof globalThis !== 'undefined' ? globalThis : this);\n";
fs.writeFileSync(OUT, out);
console.log(path.relative(root, OUT) + ':', total, 'emoji in', data.length, 'groups,', toned, 'with skin tones,', (out.length / 1024).toFixed(0) + ' KB');
