#!/usr/bin/env bash
# Exports design/sweeter-icon.svg to every PNG the app and the Safari
# extension use. Needs rsvg-convert (brew install librsvg).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SVG="$ROOT/design/sweeter-icon.svg"
python3 "$ROOT/design/sweeter-icon.py"
SET="$ROOT/safari/Sweeter/Sweeter/Assets.xcassets/AppIcon.appiconset"
for s in 16 32 128 256 512; do
  rsvg-convert -w "$s" -h "$s" "$SVG" -o "$SET/mac-icon-$s@1x.png"
  rsvg-convert -w $((s * 2)) -h $((s * 2)) "$SVG" -o "$SET/mac-icon-$s@2x.png"
done
for s in 16 32 48 96 128 256 512; do
  rsvg-convert -w "$s" -h "$s" "$SVG" -o "$ROOT/extension/icons/icon-$s.png"
done
rsvg-convert -w 1024 -h 1024 "$SVG" -o "$ROOT/design/icon-1024.png"
# The loading screen shows the icon itself.
printf "// Generated by scripts/icons.sh from design/sweeter-icon.svg. Do not edit.\n(function (root) {\n  (root.Sweeter || (root.Sweeter = {})).MARK = 'data:image/svg+xml;base64,%s';\n})(typeof globalThis !== 'undefined' ? globalThis : this);\n" "$(base64 < "$SVG" | tr -d '\n')" > "$ROOT/extension/src/ui/mark.js"
echo "Icons exported from design/sweeter-icon.svg"
