#!/usr/bin/env bash
# The loading screen's flapping bird: design/loader/sweeter-loader-sprite.png
# (starl3xx's eight 256 px poses in a row, 130 ms each, looped) as one WebP
# at 240 px cells (2x the 120 pt it shows at), for the page
# (extension/src/ui/loader.js, inline, since X Pro's page allows no other
# image host) and the Mac app's first screen (extension/src/ui/loader.webp,
# read from the bundle). Needs cwebp (brew install webp).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
sips -z 240 1920 "$ROOT/design/loader/sweeter-loader-sprite.png" --out "$TMP/sprite.png" >/dev/null
cwebp -quiet -q 90 -alpha_q 90 -m 6 -sharp_yuv "$TMP/sprite.png" -o "$ROOT/extension/src/ui/loader.webp"
printf "// Generated by scripts/loader.sh from design/loader/sweeter-loader-sprite.png. Do not edit.\n(function (root) {\n  (root.Sweeter || (root.Sweeter = {})).LOADER = 'data:image/webp;base64,%s';\n})(typeof globalThis !== 'undefined' ? globalThis : this);\n" "$(base64 < "$ROOT/extension/src/ui/loader.webp" | tr -d '\n')" > "$ROOT/extension/src/ui/loader.js"
echo "Loader exported from design/loader/sweeter-loader-sprite.png"
